# Notebook 1: Dataset Understanding

## Business Question
What does a single accident record represent?

### Observation
Each row represents one unique road accident record containing information about its location, date and time, weather conditions, road characteristics, traffic conditions, accident severity, vehicles involved, and casualties.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
df = pd.read_excel("indian_roads_dataset21.xlsx")

In [3]:
df.head()

,city,state,latitude,longitude,date,time,day_of_week,road_type,traffic_signal,weather,visibility,traffic_density,cause,accident_severity,vehicles_involved,casualties
0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,05:00:00,Sunday,highway,1,fog,low,high,weather,fatal,2,2
1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,04:00:00,Sunday,urban,0,clear,high,low,weather,major,4,3
2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00:00,Wednesday,urban,0,fog,low,medium,weather,minor,1,1
3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00:00,Sunday,urban,1,fog,low,high,distraction,minor,5,2
4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00:00,Thursday,highway,1,clear,high,low,distraction,minor,2,1

## Business Question
Does the dataset remain consistent from the beginning to the end?

In [4]:
df.tail()

,city,state,latitude,longitude,date,time,day_of_week,road_type,traffic_signal,weather,visibility,traffic_density,cause,accident_severity,vehicles_involved,casualties
19995,Bangalore,Karnataka,13.092276,77.599571,2022-09-29,03:00:00,Thursday,urban,1,clear,high,low,distraction,minor,3,2
19996,Chennai,Tamil Nadu,13.172928,80.157062,2023-11-25,01:00:00,Saturday,urban,1,clear,high,low,distraction,major,4,2
19997,Chennai,Tamil Nadu,12.997170,80.150724,2022-06-18,15:00:00,Saturday,rural,0,clear,high,low,weather,minor,3,3
19998,Kolkata,West Bengal,22.454882,88.322213,2023-03-12,04:00:00,Sunday,highway,1,clear,high,low,poor road,minor,1,0
19999,Delhi,Delhi,28.510266,77.065301,2024-07-05,23:00:00,Friday,highway,1,rain,low,high,overspeeding,minor,4,2

## Business Question
How large is the dataset?

In [5]:
df.shape

(20000, 16)

### Observation
The dataset contains **20,000 rows** and **16 columns**, providing sufficient records for meaningful analysis and pattern discovery.

## Business Question
What information is available in the dataset?

In [6]:
df.columns

Index(['city', 'state', 'latitude', 'longitude', 'date', 'time', 'day_of_week',
       'road_type', 'traffic_signal', 'weather', 'visibility',
       'traffic_density', 'cause', 'accident_severity', 'vehicles_involved',
       'casualties'],
      dtype='str')

<!-- Business Question: What information is available in the dataset?
OBSERVATION: The dataset contains columns related to accident location, date and time, weather conditions, traffic conditions, road characteristics, accident severity, and geographical coordinates. These columns provide sufficient information to perform location-based, time-based, environmental, traffic, and severity analysis. -->
DATASET DICTIONARY
| Column            | Type        | Purpose                    |
| ----------------- | ----------- | -------------------------- |
| city              | Categorical | Accident location (city)   |
| state             | Categorical | Accident location (state)  |
| latitude          | Float       | Hotspot mapping            |
| longitude         | Float       | Hotspot mapping            |
| date              | Date        | Time-based analysis        |
| time              | Time        | Peak hour analysis         |
| day_of_week       | Categorical | Weekly trends              |
| road_type         | Categorical | Road analysis              |
| traffic_signal    | Categorical | Traffic analysis           |
| weather           | Categorical | Weather analysis           |
| visibility        | Categorical | Visibility analysis        |
| traffic_density   | Categorical | Traffic condition analysis |
| cause             | Categorical | Accident cause analysis    |
| accident_severity | Categorical | Severity analysis          |
| vehicles_involved | Integer     | Accident scale             |
| casualties        | Integer     | Accident impact            |

## Business Question

What are the data types and memory usage of the dataset?

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   city               20000 non-null  str
 1   state              20000 non-null  str
 2   latitude           20000 non-null  float64
 3   longitude          20000 non-null  float64
 4   date               20000 non-null  datetime64[us]
 5   time               20000 non-null  object
 6   day_of_week        20000 non-null  str
 7   road_type          20000 non-null  str
 8   traffic_signal     20000 non-null  int64
 9   weather            20000 non-null  str
 10  visibility         20000 non-null  str
 11  traffic_density    20000 non-null  str
 12  cause              20000 non-null  str
 13  accident_severity  20000 non-null  str
 14  vehicles_involved  20000 non-null  int64
 15  casualties         20000 non-null  int64
dtypes: datetime64[us](1), float64(2), int64(3), object(1), str(9)
memory usage: 3.5+ MB

### Observation

- Total Rows: **20,000**
- Total Columns: **16**
- Data Types: datetime, float, integer, and categorical variables.
- No missing records were observed in the dataset structure.

The dataset is well-structured and suitable for further analysis.

## Business Question
What are the basic statistics of the numerical columns?

In [8]:
df.describe()

,latitude,longitude,date,traffic_signal,vehicles_involved,casualties
count,20000.000000,20000.000000,20000,20000.000000,20000.000000,20000.000000
mean,20.389207,78.173330,2023-08-22 07:04:48,0.499850,2.992000,1.726450
min,12.800172,72.700017,2022-01-01 00:00:00,0.000000,1.000000,0.000000
25%,13.198653,73.997979,2022-10-25 00:00:00,0.000000,2.000000,1.000000
50%,18.812008,77.297000,2023-08-21 00:00:00,0.000000,3.000000,1.000000
75%,28.402467,80.111089,2024-06-21 00:00:00,1.000000,4.000000,3.000000
max,30.799960,88.499861,2025-04-15 00:00:00,1.000000,5.000000,5.000000
std,6.165791,4.485967,NaN,0.500012,1.415534,1.489104

### Observation

The numerical summary indicates that:

- The dataset contains complete numerical records.
- Accident records span from **January 2022 to April 2025**.
- On average, around **3 vehicles** are involved in each accident.
- The average number of casualties is approximately **2 per accident**.

The variation across numerical variables makes the dataset suitable for identifying accident patterns and severity trends.

## Business Question
What are the characteristics of the categorical columns?

In [9]:
df.describe(include="object")

C:\Users\Niyati\AppData\Local\Temp\ipykernel_3620\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,city,state,time,day_of_week,road_type,weather,visibility,traffic_density,cause,accident_severity
count,20000,20000,20000,20000,20000,20000,20000,20000,20000,20000
unique,8,7,24,7,3,3,3,3,5,3
top,Chandigarh,Maharashtra,02:00:00,Monday,urban,clear,low,low,distraction,minor
freq,2577,5009,888,2966,6745,6690,9987,7067,4026,11025

## Observation

The categorical summary provides:

- Number of unique categories.
- Most frequent category.
- Frequency of the most common category.

This helps understand the distribution of accident-related attributes and identify dominant categories.

## Business Question

Does the dataset contain any missing values?

In [10]:
df.isna().sum()

city                 0
state                0
latitude             0
longitude            0
date                 0
time                 0
day_of_week          0
road_type            0
traffic_signal       0
weather              0
visibility           0
traffic_density      0
cause                0
accident_severity    0
vehicles_involved    0
casualties           0
dtype: int64

### Observation
No missing values were found in any column.
The dataset is complete and ready for further analysis without requiring any missing value treatment.

## Business Question
Does the dataset contain duplicate accident records?

In [11]:
df.duplicated().sum()

np.int64(0)

### Observation
No duplicate records were found.
Each row represents a unique accident record, ensuring the reliability of subsequent analyses.

## Business Question
How many unique values are present in each column?

In [12]:
df.nunique()

city                     8
state                    7
latitude             19907
longitude            19927
date                  1201
time                    24
day_of_week              7
road_type                3
traffic_signal           2
weather                  3
visibility               3
traffic_density          3
cause                    5
accident_severity        3
vehicles_involved        5
casualties               6
dtype: int64

### Observation
The unique value count helps distinguish categorical variables with limited categories from columns with many unique values, such as dates, cities, and geographical coordinates.
This information assists in selecting appropriate visualization and analysis techniques.

## Dataset Summary
The dataset contains historical road accident records with information related to accident location, time, weather conditions, traffic conditions, road characteristics, accident severity, vehicles involved, and casualties.
The dataset is clean, contains no missing or duplicate values, and is fully prepared for Exploratory Data Analysis (EDA).

## Key Takeaways
- The dataset is clean and analysis-ready.
- It contains both numerical and categorical variables.
- The data supports location, time, environmental, traffic, and severity analysis.
- Latitude and longitude enable geographical hotspot mapping.
- The dataset is suitable for building interactive dashboards and generating actionable road safety insights.

## Business Conclusion
The dataset provides a strong foundation for road accident analysis. Its completeness and diversity enable meaningful insights into accident patterns, geographical hotspots, traffic conditions, environmental factors, and accident severity.
The findings from this notebook will support advanced analyses such as Exploratory Data Analysis, Location Intelligence, Risk Intelligence, and the development of an interactive RoadScape dashboard.

<!-- Business Question :How many unique values are present in each column?
Observation:
The unique value count helps identify the diversity of each column. It distinguishes categorical variables with limited categories from columns with many unique values, such as dates, locations, and geographical coordinates. This information helps determine the most suitable analysis and visualization techniques. -->

<!-- DATASET SUMMARY
The dataset contains historical road accident records with information related to accident location, time, weather conditions, traffic conditions, road characteristics, and accident severity. The dataset is clean, contains no missing or duplicate values, and is ready for Exploratory Data Analysis. -->

<!-- Key Takeaways:
The dataset is clean and ready for analysis.
It contains both numerical and categorical variables.
The data supports location, time, environmental, traffic, and severity analysis.
Latitude and longitude enable geographical mapping.
The dataset is suitable for building an interactive road safety dashboard -->